### ISSUE TITLE
Please provide the command to intstall in colab

### ISSUE THREAD

**Issue by azizcu** [gchochla/VAuLT#1]
which command do I have use to install "VAuLT" in Google Colab?

**Comment by gchochla** [comment]
I'm also having some trouble setting up VAuLT in Google Colab's environment, I'm trying to figure this out. Apologies for the inconvenience!

**Comment by gchochla** [comment]
You can now successfully install using `!pip install git+https://github.com/gchochla/VAuLT.git@main`. Thanks for bringing this to my attention!
