### ISSUE TITLE
REL link

### ISSUE THREAD

**Issue by Ma-PC** [gchochla/VAuLT#11]
”REL @ git+https://github.com/informagi/REL.git@635429a49cb3de3d8f5f27838cb4e41905e058be”
This link no longer exists, so I should try to replace it with a commit hash？

**Comment by gchochla** [comment]
Hey! The actual URL is: https://github.com/informagi/REL/commit/635429a49cb3de3d8f5f27838cb4e41905e058be, but the URL as formatted above is the correct format for the setup.py, which you can use to install packages with `pip install -e .`, as shown in the README.
