### ISSUE TITLE
RuntimeError: The size of tensor a (128) must match the size of tensor b (40) at non-singleton dimension 1

### ISSUE THREAD

**Issue by azizcu** [gchochla/VAuLT#3]
encoding = self.processor(image, text, padding="max_length", truncation=True, return_tensors="pt",max_length=128)

Got this runtime error. Can I set max_length= 128 or more? If yes, please help how can I do it?

**Comment by gchochla** [comment]
ViLT's position embeddings for text are trained embeddings, and up to 40 are available. I can provide a flag that skips ViLT's embeddings so that you can use as many as the LM will allow.

**Comment by azizcu** [comment]
But I got the runtime error for VAuLT mode when set max_length=128. Can you please write a code portion, about how to use max_length= 128 or more for VAuLT?  or how to use a flag for it?
Thanks for your cooperation.

**Comment by gchochla** [comment]
VAuLT is using ViLT internally, and therefore inherits this restriction

**Comment by gchochla** [comment]
If you reinstall the package now, you can do:

```python
model = VaultModel.from_pretrained(
    vilt_model_name_or_path,
    bert_model_name_or_path
    use_vilt_position_embeddings=False,
)
```

This will skip ViLT's position embeddings for text, and you can expand the `max_length` to however long the language model can accommodate.
