### ISSUE TITLE
about corrupt_ids.txt

### ISSUE THREAD

**Issue by durianer-D** [gchochla/VAuLT#5]
Hello, I would like to use the MVSA dataset. Where should I obtain the corrupt_ids.txt file?

**Comment by gchochla** [comment]
Ideally, you should build it yourself by finding which images are corrupted in your local copy of the dataset. For me, the `corrupt_ids.txt` looks like this
```
3151
3910
5995
```
for MVSA-Multiple, whereas I didn't have any issues with MVSA-Single

**Comment by durianer-D** [comment]
Ok, thank you for your help!
